name: Velcro CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/release.yml"
      - ".*ignore"
      - "LICENSE"
      - "README.md"

concurrency: publish

jobs:

  verified:
    uses: ./.github/workflows/verify.yml

  prerelease:
    name: Publish @next to npm
    needs: verified
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install deps
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Increment version
        id: semver
        run: |
          VERSION=$(npm version prerelease --no-git-tag-version | tr -d '[:space:]')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Publish prerelease
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --public --tag next
      - name: Bump ver > git
        run: |
          git config --global user.name "Adam McKee"
          git config --global user.email "adam.be.g84d@gmail.com"
          git commit -am "increment @eighty4/velcro@next to ${{steps.semver.outputs.version}}"
          git push
    outputs:
      version: ${{steps.semver.outputs.version}}

  docker:
    name: Docker build and push
    needs: prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: 84tech
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: docker
        env:
          VERSION: ${{needs.prerelease.outputs.version}}
        run: |
          docker build -t 84tech/velcro:$VERSION --build-arg VELCRO_VERSION=$VERSION .
          docker push 84tech/velcro:$VERSION
