name: Verify

on:
  workflow_call:
  pull_request:
    branches: [ main ]

jobs:

  verified:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - build
    steps:
      - run: echo "C G Em Am E C G Em Am E7 Am"

  test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:8.7.0
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health"
          --health-start-period 30s
          --health-interval 5s
          --health-retries 20
          --health-timeout 5s
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm build
